// Joins raw D1 counts with the versioned score run bundled in lib/score-run.js.
// Raw records live in D1; the computed run (percentiles, grades, role-period
// adjustments) is generated by scripts/compute-scores-stage3.cjs and deployed
// with the code so the API and the page that explains it never disagree.
import RUN from './score-run.js';

export const run = RUN.run;

export const MEMBER_SQL = `SELECT
  m.id, m.name, m.hanja_name, m.party, m.district, m.committee,
  m.term_start, m.term_end, m.tenure_days,
  l.lead_count, l.lead_passed, l.lead_alternative, l.lead_withdrawn, l.lead_rejected, l.lead_pending, l.co_lead_count, l.weighted_score,
  v.eligible_count as vote_eligible, v.participated_count as vote_participated, v.excluded_count as vote_excluded, v.participation_rate,
  a.meetings_total as attendance_meetings, a.present_count as attendance_present, a.absent_count, a.leave_count, a.travel_count, a.attendance_rate,
  c.months_covered as committee_months_covered, c.meetings_total as committee_meetings_total, c.present_count as committee_present, c.absent_count as committee_absent, c.leave_count as committee_leave, c.travel_count as committee_travel, c.attendance_rate as committee_attendance_rate
FROM members m
LEFT JOIN member_legislation l ON l.member_id = m.id
LEFT JOIN member_votes v ON v.member_id = m.id
LEFT JOIN member_attendance a ON a.member_id = m.id
LEFT JOIN member_committee_attendance c ON c.member_id = m.id`;

const SCORE_FIELDS = [
  'status', 'eligible', 'observed_days', 'legislation_percentile', 'vote_percentile', 'attendance_percentile',
  'committee_attendance_percentile', 'composite_percentile', 'composite_score', 'coop_bonus', 'coop_index', 'coop_excess', 'rank', 'grade',
];

// Returns the row with score fields attached. For members with an excluded
// office period, the record fields are replaced by the scored (adjusted)
// values and the original D1 values are kept under `raw`.
export function withScores(row) {
  const s = RUN.scores[row.id] || { status: 'unscored', eligible: 0 };
  // documented corrections to the raw record come first
  const out = { ...row, ...(s.correct || {}) };
  for (const k of SCORE_FIELDS) out[k] = s[k] ?? null;
  out.eligible = s.eligible || 0;
  if (s.scored) {
    out.raw = {};
    for (const k of Object.keys(s.scored)) out.raw[k] = k in (s.correct || {}) ? s.correct[k] : row[k];
    Object.assign(out, s.scored);
  }
  out.roles = RUN.roles.filter((r) => r.member_id === row.id);
  return out;
}

export const byRank = (a, b) =>
  (a.rank === null) - (b.rank === null) || (a.rank ?? 0) - (b.rank ?? 0) || a.name.localeCompare(b.name, 'ko');
